# Site name
site_name: CompressFly
repo_url: https://github.com/shirhana/intro-final-proj

# Navigation menu
nav:
  - Code Reference: reference/  
  - Home: index.md
  - Introduction: introduction.md
  - Install: install.md
  - Configuration: configuration.md
  - Example: example.md
  - Development: development.md
  - Deployment: deployment.md
  - Release notes: release_notes.md
  
# Theme
theme:
    feaures:
      - tabs
    name: material
    icon:
      logo: material/cloud
    font:
      text: Ubuntu
      code: Ubuntu Mono
    static_templates:
      - 404.html
    palette:

      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default 
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
        primary: deep purple
        accent: teal

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
        primary: deep purple
        accent: teal
   
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md 
  - mkdocstrings
  - pdf-export:
      verbose: True
      media_type: print
      combined: True
      combined_output_path: pdf/combined.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/shirhana

copyright: Copyright &copy; 2024 Shir Hana Stern
